export enum PredictTableActionTypes {
  UPDATE_TABLE_DATA = 'UPDATE_PREDICT_TABLE_DATA',
  UPDATE_TABLE_DATA_CELL = 'UPDATE_PREDICT_TABLE_DATA_CELL',
  SET_TABLE_HEADERS = 'SET_PREDICT_TABLE_HEADERS',
  SET_TABLE_HEADERS_WITH_TEXT = 'SET_PREDICT_TABLE_HEADERS_WITH_TEXT',
  UPDATE_TABLE_HEADER_TEXT = 'UPDATE_PREDICT_TABLE_HEADER_TEXT',
}
