export enum TrainTableActionTypes {
  UPDATE_TABLE_DATA = 'UPDATE_TRAIN_TABLE_DATA',
  UPDATE_TABLE_DATA_CELL = 'UPDATE_TRAIN_TABLE_DATA_CELL',
  SET_TABLE_HEADERS = 'SET_TRAIN_TABLE_HEADERS',
  SET_TABLE_HEADERS_WITH_TEXT = 'SET_TRAIN_TABLE_HEADERS_WITH_TEXT',
  UPDATE_TABLE_HEADER_TEXT = 'UPDATE_TRAIN_TABLE_HEADER_TEXT',
}
